version: '3.8'

services:
  frontend:
    image: frontend
    build: ./example-frontend
    ports:
      - 5000:5000

  backend:
    image: backend
    build: ./example-backend
    ports:
      - 8080:8080
