services:
  frontend:
    image: frontend
    build: ./example-frontend
    ports:
      - 5000:5000
    container_name: Frontend

  backend:
    image: backend
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    container_name: Backend

  db:
    image: postgres
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis-db
